name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - requests=2.24.0
  - python=3.9
  - pip=20.3.3
  - mlflow=2.0.1
  - hydra-core=1.0.6
  - numpy=1.23.5
  - pip:
      - wandb==0.10.21
      - hydra-joblib-launcher==1.1.2
