name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=1.2.3
  - pip=20.3.3
  - python=3.8
  - pytest=6.2.2
  - scipy=1.6.1
  - numpy=1.23.5
  - pip:
      - wandb==0.10.21