name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=1.2.3
  - pip=20.3.3
  - python=3.8
  - scikit-learn=0.24.1
  - plotly==4.4.1
  - pillow=8.1.2
  - mlflow=1.14.1
  - numpy=1.23.5
  - pip:
      - wandb==0.10.21
      - matplotlib==3.2.2
